# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0004_auto_20180505_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='i_image',
            field=models.ImageField(null='NONE', upload_to='upload'),
        ),
    ]
