# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=256)),
                ('outtime', models.DateTimeField(null=True)),
                ('t', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.UserModel')),
            ],
            options={
                'db_table': 'axf_users_info',
            },
        ),
    ]
